apiVersion: v1
kind: Service
metadata:
  name: java-servlet-service
spec:
  selector:
    app: java-servlet
  ports:
    - protocol: TCP
      port: 80  # Expose on port 80 externally
      targetPort: 8080  # Match the container port
  type: NodePort  # Use "LoadBalancer" for cloud environments or "ClusterIP" for an internal service
